"""Public tutorial API for the DIMER SwinV2 image-classification pipeline (carried by the notebook)."""

from .pipeline import (
    BASE_MODEL_CATALOG,
    DECISION_RULE,
    DEFAULT_WEIGHTS_DIR,
    INPUT_SCHEMA,
    METRIC_IDS,
    MIN_CLASSES,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    WEIGHTS_SHA256,
    SwinClassificationPipeline,
    ValidationFailure,
    evaluation_report,
    generate_synthetic_sample,
    inspect_dataset,
    majority_class_baseline,
    safe_extract_zip,
    stage_missing_files,
    validate_dataset,
    validate_inputs,
    verify_artifact_generation,
    verify_snapshot,
)

__all__ = [
    "BASE_MODEL_CATALOG",
    "DECISION_RULE",
    "DEFAULT_WEIGHTS_DIR",
    "INPUT_SCHEMA",
    "METRIC_IDS",
    "MIN_CLASSES",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "WEIGHTS_SHA256",
    "SwinClassificationPipeline",
    "ValidationFailure",
    "evaluation_report",
    "generate_synthetic_sample",
    "inspect_dataset",
    "majority_class_baseline",
    "safe_extract_zip",
    "stage_missing_files",
    "validate_dataset",
    "validate_inputs",
    "verify_artifact_generation",
    "verify_snapshot",
]
