"""Static checks for the Swin classification tutorial — delegates to tools/validate_release_assets.py.

The notebook is a standalone carrier under DIMER Notebook Specification 1.1 (§3.6), generated by
tools/build_notebook.py; the fleet validator owns every source invariant (carrier, parity, identity, profile
markers, forbidden patterns, registry and model-card consistency). This entry point is kept so the
`verify-image-release.yml` step and the tutorial registry keep their documented command.

This validates source structure only. It must never be cited as REL1/REL5 execution evidence.
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    target = ROOT / "tools" / "validate_release_assets.py"
    spec = importlib.util.spec_from_file_location("validate_release_assets", target)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return int(module.main())


if __name__ == "__main__":
    sys.exit(main())
